# Site settings
title: Your awesome title
subtitle: Your awesome subtitle
email: your-email@domain.com
logo: /img/logo.svg
favicon: /img/logo.svg
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.www.com" # the base hostname & protocol for your site


permalink: /post/:year/:month/:day/:title.html
paginate: 1
paginate_path: blog/page:num
github: https://github.com/BenBBear/Zeta/
footer_github: https://github.com/BenBBear/Zeta/tree/gh-pages


# Build settings
markdown: kramdown
collections:
  guide:
    output: true
    permalink: /guide/:path.html




gems:
  - jekyll-sitemap
