# Site settings
title: Zetajs
description: > # this means to ignore newlines until "baseurl:"
    Zetajs Home Page
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zetajs.io" # the base hostname & protocol for your site
github_username:  BenBBear

# Build settings
markdown: kramdown
